### PR TITLE
WIP new single project template

### PR DESCRIPTION
**Pull request by davidortinau**
removed the old template too. Need to work out build dependencies.

### CODE REVIEW

**Comment by davidortinau** [comment]
Current errors I'm getting when trying to build.

## Android 

```cli
dotnet build -t:Run -f net6.0-android
```

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/30.0.100-preview.5.19/tools/Xamarin.Android.Common.targets(504,3): error XA1018: Specified AndroidManifest file does not exist: /Users/dmo/work/demos/App4/App4/AndroidManifest.xml. [/Users/dmo/work/demos/App4/App4/App4.csproj]
```

## Mac Catalyst

```
dotnet build -t:Run -f net6.0-maccatalyst
```

```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.5.884/tools/msbuild/iOS/Xamarin.Shared.targets(759,3): error : Info.plist not found. [/Users/dmo/work/demos/App4/App4/App4.csproj]
```

@redth or @jonathanpeppers - advice on those errors and what to do with `Directory.Build.targets`? I brought in the maui template to start, but it's quite different from what @Clancey is doing here.

**Review by jonathanpeppers — COMMENTED** [review]
Right now you only have 2 MAUI packages:
```xml
    <PackageReference Include="Microsoft.Maui.Core" Version="MAUI_VERSION" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="MAUI_VERSION" />
```

I believe that `Microsoft.Maui.Controls.Build.Tasks` and `Microsoft.Maui.Resizetizer` would be needed for `<SingleProject>true</SingleProject>` to work.

Can these all just be setup as dependencies for Comet, so you don't have to put them in the template at all?

**Comment by jonathanpeppers** [comment]
How this works would also change when we merge: https://github.com/dotnet/maui/pull/603

You would put `<UseMauiCore>true</UseMauiCore>` and `<UseMauiAssets>true</UseMauiAssets>`. Which, perhaps, Comet could implicitly set somehow from MSBuild targets inside the NuGet package.

**Comment by saint4eva** [comment]
Please make it very easy for getting started

**Comment by Clancey** [comment]
> Microsoft.Maui.Controls.Build.Tasks

This seems like it's the wrong namespace. Or we need 2 build tasks. But Comet shouldn't require anything from Controls.

**Pull request merged**
